[package]
name = "cot_tailwindcss"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.14"
cot = { version = "0.3.1", features = ["full"] }
futures = "0.3.31"
tower = "0.5.2"
tower-service = "0.3.3"
